version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1"
      timezone: "America/Mexico_City"
    target-branch: "dev"
    
    groups:
      angular-normal:
        patterns:
          - "@angular/*"
        update-types:
          - "patch"
          - "minor"
      eslint-normal:
        patterns:
          - "eslint"
          - "typescript-eslint"
          - "@typescript-eslint/*"
        update-types:
          - "patch"
          - "minor"
      vitest-normal:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1"
      timezone: "America/Mexico_City"
    target-branch: "dev"
