version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1"
      timezone: "America/Mexico_City"
    target-branch: "dev"
    cooldown:
      default-days: 1

    ignore:
      # Angular 22 does not support Typescript 7.x
      - dependency-name: "typescript"
        versions: "^7.0.0"
    
    groups:
      maint-angular:
        patterns:
          - "@angular/*"
        update-types:
          - "patch"
          - "minor"
      break-angular:
        patterns:
          - "@angular/*"
        update-types:
          - "major"
      
      maint-eslint:
        patterns:
          - "eslint"
          - "typescript-eslint"
          - "@typescript-eslint/*"
        update-types:
          - "patch"
          - "minor"
      break-eslint:
        patterns:
          - "eslint"
          - "typescript-eslint"
          - "@typescript-eslint/*"
        update-types:
          - "major"

      maint-angular-eslint:
        patterns:
          - "angular-eslint"
          - "@angular-eslint/*"
        update-types:
          - "patch"
          - "minor"
      break-angular-eslint:
        patterns:
          - "angular-eslint"
          - "@angular-eslint/*"
        update-types:
          - "major"

      maint-vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types:
          - "patch"
          - "minor"
      break-vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1"
      timezone: "America/Mexico_City"
    target-branch: "dev"
    cooldown:
      default-days: 1
