name: Release and create Promotion PR

on:
  push:
    branches:
      - nightly
      - dev
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  release:
    if: github.event.head_commit.message != 'chore(release):' && !contains(github.event.head_commit.message, '[skip ci]')
    uses: ./.github/workflows/semantic-release-pnpm.yml
    with:
      environment: deploy-zone
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  create-pr-nightly:
    needs: release
    if: success() && github.ref_name == 'nightly'
    uses: ./.github/workflows/create-pr.yml
    with:
      source-branch: nightly
      destination-branch: dev
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  create-pr-dev:
    needs: release
    if: success() && github.ref_name == 'dev'
    uses: ./.github/workflows/create-pr.yml
    with:
      source-branch: dev
      destination-branch: main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

